# Generated by Django 5.0.6 on 2025-05-14 20:19

from django.db import migrations
from django.db.migrations import RunPython

def create_sports_and_courts(apps, schema_editor):
    Sport = apps.get_model('booking', 'Sport')
    Court = apps.get_model('booking', 'Court')

    sports_data = [
        { 'id': 'badminton', 'name': 'Badminton', 'courts': ['Court 1', 'Court 2', 'Court 3'] },
        { 'id': 'volleyball', 'name': 'Volleyball', 'courts': ['Court 1', 'Court 2'] },
        { 'id': 'basketball', 'name': 'Basketball', 'courts': ['Main Court', 'Practice Court'] },
        { 'id': 'squash', 'name': 'Squash', 'courts': ['Court 1', 'Court 2'] },
        { 'id': 'tabletennis', 'name': 'Table Tennis', 'courts': ['Table 1', 'Table 2', 'Table 3'] },
        { 'id': 'cricketindoor', 'name': 'Cricket', 'courts': ['Pitch 1', 'Pitch 2', 'Pitch 3'] }
    ]

    for sport_data in sports_data:
        sport, created = Sport.objects.update_or_create(
            id=sport_data['id'],
            defaults={ 'name': sport_data['name'] }
        )
        for court_name in sport_data['courts']:
            Court.objects.update_or_create(
                sport=sport,
                name=court_name
            )

def reverse_migration(apps, schema_editor):
    Sport = apps.get_model('booking', 'Sport')
    Sport.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        RunPython(create_sports_and_courts, reverse_migration),
    ]
