# Generated by Django 5.0.6 on 2025-05-14 20:23

from django.db import migrations
from django.db.migrations import RunPython

def create_time_slots(apps, schema_editor):
    # Get the TimeSlot model
    TimeSlot = apps.get_model('booking', 'TimeSlot')

    # Create time slots from 7:00 AM to 10:00 PM (7-22 hours)
    for hour in range(7, 23):  # 7 AM to 10 PM
        TimeSlot.objects.update_or_create(
            hour=hour,
            minute=0
        )

def reverse_migration(apps, schema_editor):
    # Delete all time slots
    TimeSlot = apps.get_model('booking', 'TimeSlot')
    TimeSlot.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_create_sports_and_courts'),
    ]

    operations = [
        RunPython(create_time_slots, reverse_migration),
    ]
